version: "3"

services:

  vsftpd:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: ftp-custom
    container_name: ftp
    restart: always
    ports:
      - 0.0.0.0:20:20
      - 0.0.0.0:21:21
      - 21100-21110:21100-21110
    volumes:
      - /data/ftp/data/root:/home/vsftpd/
      - /data/ftp/data/root/ftp-logs:/var/log/vsftpd
    environment:
      - FTP_USER=root
      - FTP_PASS=1234
      - PASV_ADDRESS=13.124.120.4
      - PASV_ENABLE=YES
      - PASV_MIN_PORT=21100
      - PASV_MAX_PORT=21110

